name: Backend CD - Build and Upload Image

on:
    push:
        branches: ['**']

env:
  BASE_URL: http://localhost
  PORT: 3000
  NODE_ENV: production
  DEFAULT_VERSION: 1
  HENRIK_DEV_API_KEY: 'HDEV-asd590f0-asdf-asdf-asdf-0asdf0asdf'
  SUPABASE_URL: 'https://abcdefgh.supabase.co'
  SUPABASE_KEY: 'asdf0asdf-asdf-asdf-asdf-0asdf0asdf'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download generated files
              uses: actions/download-artifact@v4
              with:
                  name: generated
                  path: .

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: vg-backend:latest   